//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "Sawczyn.Sequencer.SequencerDiagram")]

namespace Sawczyn.Sequencer
{
	/// <summary>
	/// DomainClass SequencerDiagram
	/// Description for Sawczyn.Sequencer.SequencerDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("Sawczyn.Sequencer.SequencerDiagram.DisplayName", typeof(global::Sawczyn.Sequencer.SequencerDomainModel), "Sawczyn.Sequencer.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Sawczyn.Sequencer.SequencerDiagram.Description", typeof(global::Sawczyn.Sequencer.SequencerDomainModel), "Sawczyn.Sequencer.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::Sawczyn.Sequencer.SequencerDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("6fb004cc-f0ce-4312-92e4-c821ab8a5330")]
	public partial class SequencerDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::Sawczyn.Sequencer.SequencerToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Custom storage for shape properties that appear in the property grid
		/// <summary>
		/// Custom storage for domain property FillColor.
		/// </summary>
		private global::System.Drawing.Color GetFillColorValue()
		{
			DslDiagrams::BrushSettings settings = this.StyleSet.GetOverriddenBrushSettings(DslDiagrams::DiagramBrushes.DiagramBackground);
			if(settings != null && settings.IsOverridden(DslDiagrams::BrushSettingsFlags.Color))
			{
				return settings.Color;
			}
			return global::System.Drawing.Color.FromKnownColor(global::System.Drawing.KnownColor.White);
		}
		
		/// <summary>
		/// Custom storage for domain property FillColor.
		/// </summary>
		private void SetFillColorValue(global::System.Drawing.Color newValue)
		{
			DslDiagrams::BrushSettings settings = this.StyleSet.GetOverriddenBrushSettings(DslDiagrams::DiagramBrushes.DiagramBackground);
			if(settings == null) settings = new DslDiagrams::BrushSettings();
			settings.Color = newValue;
			this.StyleSet.OverrideBrush(DslDiagrams::DiagramBrushes.DiagramBackground, settings);
			this.Invalidate();
		}
		
		#endregion
		#region Swimlane support
		
		/// <summary>
		/// Gets whether or not swimlanes are supported in this Diagram.
		/// </summary>
		public override bool HasSwimlanes
		{
			get { return true; }
		}
		
		/// <summary>
		/// Initializes the starting swimlanes in a new Diagram.
		/// </summary>
		/// <remarks>
		/// This method is not called during successful deserialization, only when either a blank diagram is created or diagram deserialization fails and a diagram is created to make things work.
		/// 
		/// This method does not create shapes for swimlanes with shape maps specified in the DSL definition, only those swimlanes which are not mapped.
		/// The assumption here is that if a swimlane is mapped to a domain class, then an instance of that class  will be created when the element mapped to the diagram is created,
		/// and swimlane shapes will be created as part of view fixup.
		/// </remarks>
		internal virtual void InitializeSwimlanes()
		{
		}
		
		/// <summary>
		/// Gets a collection of domain classes which are mapped to swimlane shapes.
		/// </summary>
		public override sealed global::System.Collections.Generic.IEnumerable<DslModeling::DomainClassInfo> CreatableSwimLaneSubjects
		{
			get
			{
				yield return this.Store.DomainDataDirectory.GetDomainClass(typeof(global::Sawczyn.Sequencer.Class));
			}
		}
		
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::Sawczyn.Sequencer.Method)
			{
				global::Sawczyn.Sequencer.MethodShape newShape = new global::Sawczyn.Sequencer.MethodShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Sawczyn.Sequencer.Branch)
			{
				global::Sawczyn.Sequencer.BranchShape newShape = new global::Sawczyn.Sequencer.BranchShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Sawczyn.Sequencer.Synchronization)
			{
				global::Sawczyn.Sequencer.SyncBarShape newShape = new global::Sawczyn.Sequencer.SyncBarShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Sawczyn.Sequencer.EndPoint)
			{
				global::Sawczyn.Sequencer.EndShape newShape = new global::Sawczyn.Sequencer.EndShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Sawczyn.Sequencer.StartPoint)
			{
				global::Sawczyn.Sequencer.StartShape newShape = new global::Sawczyn.Sequencer.StartShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Sawczyn.Sequencer.Comment)
			{
				global::Sawczyn.Sequencer.CommentBoxShape newShape = new global::Sawczyn.Sequencer.CommentBoxShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Sawczyn.Sequencer.Class)
			{
				global::Sawczyn.Sequencer.SwimLane newShape = new global::Sawczyn.Sequencer.SwimLane(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Sawczyn.Sequencer.CommentReferencesSubjects)
			{
				global::Sawczyn.Sequencer.CommentConnector newShape = new global::Sawczyn.Sequencer.CommentConnector(this.Partition);
				return newShape;
			}
			if(element is global::Sawczyn.Sequencer.FlowElementsCallCallables)
			{
				global::Sawczyn.Sequencer.CallConnector newShape = new global::Sawczyn.Sequencer.CallConnector(this.Partition);
				return newShape;
			}
			if(element is global::Sawczyn.Sequencer.CallablesReturnResults)
			{
				global::Sawczyn.Sequencer.ResultConnector newShape = new global::Sawczyn.Sequencer.ResultConnector(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::Sawczyn.Sequencer.MethodShape.DecoratorsInitialized += MethodShapeDecoratorMap.OnDecoratorsInitialized;
			global::Sawczyn.Sequencer.CommentBoxShape.DecoratorsInitialized += CommentBoxShapeDecoratorMap.OnDecoratorsInitialized;
			global::Sawczyn.Sequencer.SwimLane.DecoratorsInitialized += SwimLaneDecoratorMap.OnDecoratorsInitialized;
			global::Sawczyn.Sequencer.CallConnector.DecoratorsInitialized += CallConnectorDecoratorMap.OnDecoratorsInitialized;
			global::Sawczyn.Sequencer.ResultConnector.DecoratorsInitialized += ResultConnectorDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MethodShape.
		/// </summary>
		internal static partial class MethodShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MethodShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Sawczyn.Sequencer.Method.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for CommentBoxShape.
		/// </summary>
		internal static partial class CommentBoxShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for CommentBoxShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Sawczyn.Sequencer.Comment.TextDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Comment").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for SwimLane.
		/// </summary>
		internal static partial class SwimLaneDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for SwimLane.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Sawczyn.Sequencer.Class.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "ClassName").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Sawczyn.Sequencer.Class.AssemblyDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "AssemblyName").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for CallConnector.
		/// </summary>
		internal static partial class CallConnectorDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for CallConnector.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Sawczyn.Sequencer.Callable.ConditionDomainPropertyId);
				propertyInfo.PresentationDomainNavigator = new DslDiagrams::PresentationDomainNavigator(ConditionPresentationToDomain);
				propertyInfo.DomainPresentationNavigator = new DslDiagrams::DomainPresentationNavigator(ConditionDomainToPresentation);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Condition").AssociateValueWith(shape.Store, propertyInfo);
			}
			public static DslModeling::ModelElement ConditionPresentationToDomain(DslDiagrams::PresentationElement presentation)
			{
				global::Sawczyn.Sequencer.FlowElementsCallCallables modelElement = presentation.ModelElement as global::Sawczyn.Sequencer.FlowElementsCallCallables;
				if(modelElement != null)
				{
					// Segment 0
					global::Sawczyn.Sequencer.Callable mappedElement = modelElement.Callable;
					if ( mappedElement == null ) return null;
					return mappedElement;
				}
				return null;
			}
			public static global::System.Collections.Generic.ICollection<DslDiagrams::PresentationElement> ConditionDomainToPresentation(DslModeling::ModelElement modelElement)
			{
				global::Sawczyn.Sequencer.Callable typedElement = modelElement as global::Sawczyn.Sequencer.Callable;
				if(typedElement != null)
				{
					if(typedElement.IsDeleted)
					{
						// We cannot navigate back along a path containing deleted elements, best we can do is return the diagram
						// to ensure all visible shapes are invalidated.
						global::System.Collections.ObjectModel.ReadOnlyCollection<global::Sawczyn.Sequencer.SequencerDiagram> diagramCollection = modelElement.Store.ElementDirectory.FindElements<global::Sawczyn.Sequencer.SequencerDiagram>(true);
						global::Sawczyn.Sequencer.SequencerDiagram[] diagramArray = new global::Sawczyn.Sequencer.SequencerDiagram[diagramCollection.Count];
						diagramCollection.CopyTo(diagramArray, 0);
						return diagramArray;
					}
					// Segment 0
						global::System.Collections.ObjectModel.ReadOnlyCollection<global::Sawczyn.Sequencer.FlowElementsCallCallables> mappedElements = global::Sawczyn.Sequencer.FlowElementsCallCallables.GetLinksToCallSource(typedElement);
					global::System.Collections.Generic.List<DslDiagrams::PresentationElement> presentationList = new global::System.Collections.Generic.List<DslDiagrams::PresentationElement>();
					foreach(DslModeling::ModelElement mappedElement in mappedElements)
					{
						presentationList.AddRange(DslDiagrams::PresentationViewsSubject.GetPresentation(mappedElement));
					}
					return presentationList;
				}
				return null;
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ResultConnector.
		/// </summary>
		internal static partial class ResultConnectorDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ResultConnector.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Sawczyn.Sequencer.Callable.ReturnTypeDomainPropertyId);
				propertyInfo.PresentationDomainNavigator = new DslDiagrams::PresentationDomainNavigator(ReturnTypePresentationToDomain);
				propertyInfo.DomainPresentationNavigator = new DslDiagrams::DomainPresentationNavigator(ReturnTypeDomainToPresentation);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "ReturnType").AssociateValueWith(shape.Store, propertyInfo);
			}
			public static DslModeling::ModelElement ReturnTypePresentationToDomain(DslDiagrams::PresentationElement presentation)
			{
				global::Sawczyn.Sequencer.CallablesReturnResults modelElement = presentation.ModelElement as global::Sawczyn.Sequencer.CallablesReturnResults;
				if(modelElement != null)
				{
					// Segment 0
					global::Sawczyn.Sequencer.Callable mappedElement = modelElement.TargetCallable;
					if ( mappedElement == null ) return null;
					return mappedElement;
				}
				return null;
			}
			public static global::System.Collections.Generic.ICollection<DslDiagrams::PresentationElement> ReturnTypeDomainToPresentation(DslModeling::ModelElement modelElement)
			{
				global::Sawczyn.Sequencer.Callable typedElement = modelElement as global::Sawczyn.Sequencer.Callable;
				if(typedElement != null)
				{
					if(typedElement.IsDeleted)
					{
						// We cannot navigate back along a path containing deleted elements, best we can do is return the diagram
						// to ensure all visible shapes are invalidated.
						global::System.Collections.ObjectModel.ReadOnlyCollection<global::Sawczyn.Sequencer.SequencerDiagram> diagramCollection = modelElement.Store.ElementDirectory.FindElements<global::Sawczyn.Sequencer.SequencerDiagram>(true);
						global::Sawczyn.Sequencer.SequencerDiagram[] diagramArray = new global::Sawczyn.Sequencer.SequencerDiagram[diagramCollection.Count];
						diagramCollection.CopyTo(diagramArray, 0);
						return diagramArray;
					}
					// Segment 0
						global::System.Collections.ObjectModel.ReadOnlyCollection<global::Sawczyn.Sequencer.CallablesReturnResults> mappedElements = global::Sawczyn.Sequencer.CallablesReturnResults.GetLinksToResultSource(typedElement);
					global::System.Collections.Generic.List<DslDiagrams::PresentationElement> presentationList = new global::System.Collections.Generic.List<DslDiagrams::PresentationElement>();
					foreach(DslModeling::ModelElement mappedElement in mappedElements)
					{
						presentationList.AddRange(DslDiagrams::PresentationViewsSubject.GetPresentation(mappedElement));
					}
					return presentationList;
				}
				return null;
			}
		}
		
		#endregion
		
		#region Connect actions
		private bool changingMouseAction;
		private global::Sawczyn.Sequencer.FlowConnectAction flowConnectAction;
		private global::Sawczyn.Sequencer.CommentSubjectsConnectAction commentSubjectsConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::Sawczyn.Sequencer.SequencerToolboxHelper.FlowFilterString))
				{
					if (this.flowConnectAction == null)
					{
						this.flowConnectAction = new global::Sawczyn.Sequencer.FlowConnectAction(this);
						this.flowConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.flowConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::Sawczyn.Sequencer.SequencerToolboxHelper.CommentSubjectsFilterString))
				{
					if (this.commentSubjectsConnectAction == null)
					{
						this.commentSubjectsConnectAction = new global::Sawczyn.Sequencer.CommentSubjectsConnectAction(this);
						this.commentSubjectsConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.commentSubjectsConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom connect action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.flowConnectAction != null)
					{
						this.flowConnectAction.Dispose();
						this.flowConnectAction = null;
					}
					if(this.commentSubjectsConnectAction != null)
					{
						this.commentSubjectsConnectAction.Dispose();
						this.commentSubjectsConnectAction = null;
					}
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// SequencerDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x6fb004cc, 0xf0ce, 0x4312, 0x92, 0xe4, 0xc8, 0x21, 0xab, 0x8a, 0x53, 0x30);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public SequencerDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public SequencerDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region FillColor domain property code
		
		/// <summary>
		/// FillColor domain property Id.
		/// </summary>
		public static readonly global::System.Guid FillColorDomainPropertyId = new global::System.Guid(0x192c0154, 0x6473, 0x4142, 0x9d, 0x8c, 0x46, 0x44, 0xa3, 0x7f, 0xd4, 0xba);
		
		/// <summary>
		/// Gets or sets the value of FillColor domain property.
		/// Description for Sawczyn.Sequencer.SequencerDiagram.Fill Color
		/// </summary>
		[DslDesign::DisplayNameResource("Sawczyn.Sequencer.SequencerDiagram/FillColor.DisplayName", typeof(global::Sawczyn.Sequencer.SequencerDomainModel), "Sawczyn.Sequencer.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("Sawczyn.Sequencer.SequencerDiagram/FillColor.Description", typeof(global::Sawczyn.Sequencer.SequencerDomainModel), "Sawczyn.Sequencer.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainProperty(Kind = DslModeling::DomainPropertyKind.CustomStorage)]
		[DslModeling::DomainObjectId("192c0154-6473-4142-9d8c-4644a37fd4ba")]
		public global::System.Drawing.Color FillColor
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return FillColorPropertyHandler.Instance.GetValue(this);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				FillColorPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the SequencerDiagram.FillColor domain property.
		/// </summary>
		internal sealed partial class FillColorPropertyHandler : DslModeling::DomainPropertyValueHandler<SequencerDiagram, global::System.Drawing.Color>
		{
			private FillColorPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the SequencerDiagram.FillColor domain property value handler.
			/// </summary>
			public static readonly FillColorPropertyHandler Instance = new FillColorPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the SequencerDiagram.FillColor domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return FillColorDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.Drawing.Color GetValue(SequencerDiagram element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				// There is no storage for FillColor because its Kind is
				// set to CustomStorage. Please provide the GetFillColorValue()
				// method on the domain class.
				return element.GetFillColorValue();
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(SequencerDiagram element, global::System.Drawing.Color newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.Drawing.Color oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					// There is no storage for FillColor because its Kind is
					// set to CustomStorage. Please provide the SetFillColorValue()
					// method on the domain class.
					element.SetFillColorValue(newValue);
					ValueChanged(element, oldValue, GetValue(element));
				}
			}
		}
		
		#endregion
	}
}
namespace Sawczyn.Sequencer
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Sawczyn.Sequencer.Method), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Sawczyn.Sequencer.Branch), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Sawczyn.Sequencer.Synchronization), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Sawczyn.Sequencer.EndPoint), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Sawczyn.Sequencer.StartPoint), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Sawczyn.Sequencer.Comment), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Sawczyn.Sequencer.Class), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Sawczyn.Sequencer.CommentReferencesSubjects), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Sawczyn.Sequencer.FlowElementsCallCallables), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Sawczyn.Sequencer.CallablesReturnResults), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::Sawczyn.Sequencer.Method)
				{
					parentElement = GetParentForMethod((global::Sawczyn.Sequencer.Method)childElement);
				} else
				if(childElement is global::Sawczyn.Sequencer.Branch)
				{
					parentElement = GetParentForBranch((global::Sawczyn.Sequencer.Branch)childElement);
				} else
				if(childElement is global::Sawczyn.Sequencer.Synchronization)
				{
					parentElement = GetParentForSynchronization((global::Sawczyn.Sequencer.Synchronization)childElement);
				} else
				if(childElement is global::Sawczyn.Sequencer.EndPoint)
				{
					parentElement = GetParentForEndPoint((global::Sawczyn.Sequencer.EndPoint)childElement);
				} else
				if(childElement is global::Sawczyn.Sequencer.StartPoint)
				{
					parentElement = GetParentForStartPoint((global::Sawczyn.Sequencer.StartPoint)childElement);
				} else
				if(childElement is global::Sawczyn.Sequencer.Comment)
				{
					parentElement = GetParentForComment((global::Sawczyn.Sequencer.Comment)childElement);
				} else
				if(childElement is global::Sawczyn.Sequencer.Class)
				{
					parentElement = GetParentForClass((global::Sawczyn.Sequencer.Class)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::Sawczyn.Sequencer.Class GetParentForMethod( global::Sawczyn.Sequencer.FlowElement root )
			{
				// Segments 0 and 1
				global::Sawczyn.Sequencer.Class result = root.Class;
				if ( result == null ) return null;
				return result;
			}
			public static global::Sawczyn.Sequencer.SequenceDiagram GetParentForComment( global::Sawczyn.Sequencer.Comment root )
			{
				// Segments 0 and 1
				global::Sawczyn.Sequencer.SequenceDiagram result = root.SequenceDiagram;
				if ( result == null ) return null;
				return result;
			}
			public static global::Sawczyn.Sequencer.Class GetParentForBranch( global::Sawczyn.Sequencer.FlowElement root )
			{
				// Segments 0 and 1
				global::Sawczyn.Sequencer.Class result = root.Class;
				if ( result == null ) return null;
				return result;
			}
			public static global::Sawczyn.Sequencer.Class GetParentForEndPoint( global::Sawczyn.Sequencer.FlowElement root )
			{
				// Segments 0 and 1
				global::Sawczyn.Sequencer.Class result = root.Class;
				if ( result == null ) return null;
				return result;
			}
			public static global::Sawczyn.Sequencer.Class GetParentForStartPoint( global::Sawczyn.Sequencer.FlowElement root )
			{
				// Segments 0 and 1
				global::Sawczyn.Sequencer.Class result = root.Class;
				if ( result == null ) return null;
				return result;
			}
			public static global::Sawczyn.Sequencer.Class GetParentForSynchronization( global::Sawczyn.Sequencer.FlowElement root )
			{
				// Segments 0 and 1
				global::Sawczyn.Sequencer.Class result = root.Class;
				if ( result == null ) return null;
				return result;
			}
			public static global::Sawczyn.Sequencer.SequenceDiagram GetParentForClass( global::Sawczyn.Sequencer.Class root )
			{
				// Segments 0 and 1
				global::Sawczyn.Sequencer.SequenceDiagram result = root.SequenceDiagram;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
	
		/// <summary>
		/// A rule which fires when data mapped to outer text decorators has changed,
		/// so we can update the decorator host's bounds.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Sawczyn.Sequencer.Callable), InitiallyDisabled=true)]
		internal sealed class DecoratorPropertyChanged : DslModeling::ChangeRule
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Justification = "Generated code.")]
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
				
				if (e.DomainProperty.Id == global::Sawczyn.Sequencer.Callable.ConditionDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::Sawczyn.Sequencer.CallConnector.FindCallConnectorDecorator("Condition");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::Sawczyn.Sequencer.FlowElementsCallCallables.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::Sawczyn.Sequencer.Callable.ReturnTypeDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::Sawczyn.Sequencer.ResultConnector.FindResultConnectorDecorator("ReturnType");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::Sawczyn.Sequencer.CallablesReturnResults.DomainClassId);
					}
				}
			}
		}
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Sawczyn.Sequencer.CommentReferencesSubjects), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Sawczyn.Sequencer.FlowElementsCallCallables), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Sawczyn.Sequencer.CallablesReturnResults), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::Sawczyn.Sequencer.SequencerDiagram diagram = linkShape.Diagram as global::Sawczyn.Sequencer.SequencerDiagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
