//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sawczyn.Sequencer
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "sqc";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Sequencer";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Sawczyn";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID SequencerDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(SequencerCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID SequencerExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(SequencerCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewSequencerExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(SequencerCommandSetId), 0x0001);
	
		// Package identifier
		public const string SequencerPackageId = "8841b298-1d28-4f8c-8fbd-7142afbe253c";
		
		// Editor factory identifier
		public const string SequencerEditorFactoryId = "a32e65c7-c29a-4411-83e5-7124bfb09c39";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string SequencerModelExplorerToolWindowId = "f7477cf3-6f23-4b76-a884-304a3d08c9fe";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Sawczyn.Sequencer
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string SequencerCommandSetId = "5330f887-6611-4adc-83ad-a977a7ce3032";
	}
}