//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sawczyn.Sequencer
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "sqc";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Sequencer";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Sawczyn";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "0.1.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID SequencerDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(SequencerCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID SequencerExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(SequencerCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewSequencerExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(SequencerCommandSetId), 0x0001);
	
		// Package identifier
		public const string SequencerPackageId = "f653928c-67e8-4bc5-a1e1-558ebc689013";
		
		// Editor factory identifier
		public const string SequencerEditorFactoryId = "f293475e-75f9-456c-b012-d2274e3d4b87";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string SequencerModelExplorerToolWindowId = "90838454-181a-432c-9005-d15b9a32a72c";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Sawczyn.Sequencer
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string SequencerCommandSetId = "e9717e6f-c7d1-426b-a17e-ca40eb3afcb4";
	}
}